---
- name: install mongod
  hosts: all
  become: true
  tasks:
  - name: add key
    apt_key:
      url: https://www.mongodb.org/static/pgp/server-3.2.asc
      state: present


  - name: add repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  - name: update cache
    apt:
      update_cache: yes

  - name: install mongodb-org
    apt:
      name: mongodb-org
      state: present

  - name: start and enable service
    systemd:
      name: mongod
      state: started
      enabled: yes
