---
- name: Configure MongoDB
  hosts: reddit-db
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: add ip
      shell: "echo 'db: {{ansible_host}}' > /home/masterplan/var.yml"

    - name: Specifying a path directly
      fetch:
        src: /home/masterplan/var.yml
        dest: var.yml
        flat: yes

    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
  - name: restart mongod
    service: name=mongod state=restarted
